export const EXERCISE_IMAGE_MAP = {
  armCircles:      'https://yuhonas.github.io/free-exercise-db/exercises/Arm_Circles/0.jpg',
  bicepCurl:       'https://yuhonas.github.io/free-exercise-db/exercises/Dumbbell_Bicep_Curl/0.jpg',
  burpee:          'https://yuhonas.github.io/free-exercise-db/exercises/Freehand_Jump_Squat/0.jpg',
  catCow:          'https://yuhonas.github.io/free-exercise-db/exercises/Cat_Stretch/0.jpg',
  chestPress:      'https://yuhonas.github.io/free-exercise-db/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg',
  childPose:       'https://yuhonas.github.io/free-exercise-db/exercises/Childs_Pose/0.jpg',
  deepBreath:      'https://yuhonas.github.io/free-exercise-db/exercises/Stomach_Vacuum/0.jpg',
  hamstringStretch:'https://yuhonas.github.io/free-exercise-db/exercises/Hamstring_Stretch/0.jpg',
  highKnees:       'https://yuhonas.github.io/free-exercise-db/exercises/Double_Leg_Butt_Kick/0.jpg',
  hipCircles:      'https://yuhonas.github.io/free-exercise-db/exercises/Standing_Hip_Circles/0.jpg',
  hipThrust:       'https://yuhonas.github.io/free-exercise-db/exercises/Barbell_Hip_Thrust/0.jpg',
  inclineWalk:     'https://yuhonas.github.io/free-exercise-db/exercises/Walking_Treadmill/0.jpg',
  jumpRope:        'https://yuhonas.github.io/free-exercise-db/exercises/Rope_Jumping/0.jpg',
  jumpingJacks:    'https://yuhonas.github.io/free-exercise-db/exercises/Star_Jump/0.jpg',
  kbSwing:         'https://yuhonas.github.io/free-exercise-db/exercises/One-Arm_Kettlebell_Swings/0.jpg',
  latPulldown:     'https://yuhonas.github.io/free-exercise-db/exercises/Wide-Grip_Lat_Pulldown/0.jpg',
  lateralRaise:    'https://yuhonas.github.io/free-exercise-db/exercises/Side_Lateral_Raise/0.jpg',
  lunge:           'https://yuhonas.github.io/free-exercise-db/exercises/Barbell_Lunge/0.jpg',
  mountainClimber: 'https://yuhonas.github.io/free-exercise-db/exercises/Mountain_Climbers/0.jpg',
  pigeonPose:      'https://yuhonas.github.io/free-exercise-db/exercises/Runners_Stretch/0.jpg',
  plank:           'https://yuhonas.github.io/free-exercise-db/exercises/Plank/0.jpg',
  pushup:          'https://yuhonas.github.io/free-exercise-db/exercises/Push-Up_Wide/0.jpg',
  quadStretch:     'https://yuhonas.github.io/free-exercise-db/exercises/Quad_Stretch/0.jpg',
  rdl:             'https://yuhonas.github.io/free-exercise-db/exercises/Romanian_Deadlift/0.jpg',
  russianTwist:    'https://yuhonas.github.io/free-exercise-db/exercises/Cable_Russian_Twists/0.jpg',
  shoulderPress:   'https://yuhonas.github.io/free-exercise-db/exercises/Dumbbell_Shoulder_Press/0.jpg',
  shoulderStretch: 'https://yuhonas.github.io/free-exercise-db/exercises/Shoulder_Stretch/0.jpg',
  spinalTwist:     'https://yuhonas.github.io/free-exercise-db/exercises/Spinal_Stretch/0.jpg',
  squat:           'https://yuhonas.github.io/free-exercise-db/exercises/Barbell_Squat/0.jpg',
};

export const FEMALE_HERO = './ex_default_female.png';
export const MALE_HERO   = './hero_male.png';

export const EXERCISE_DESC = {
  armCircles:       'Stand tall with arms extended to your sides. Slowly rotate them forward in large circles, then reverse. Loosens shoulder joints and increases range of motion before upper-body work.',
  bicepCurl:        'Hold dumbbells at your sides, palms facing forward. Curl the weights toward your shoulders by bending at the elbow, squeezing the bicep at the top. Lower slowly in 3 seconds for maximum gains.',
  burpee:           'Start standing, drop into a squat, kick feet back into a plank, perform a push-up, jump feet forward, then explode upward with arms overhead. A full-body conditioning powerhouse that spikes heart rate fast.',
  catCow:           'On all fours, alternate between arching your back upward (cat) and letting it sag downward (cow) in rhythm with your breath. Warms up the spine and releases tension in the lower back.',
  chestPress:       'Lie on a bench or floor holding dumbbells at chest height. Press them straight up until arms are extended, then lower with control. Builds strength in the chest, shoulders, and triceps.',
  childPose:        'Kneel and sit back on your heels, then stretch your arms forward along the floor and rest your forehead down. A restorative stretch that decompresses the spine and calms the nervous system.',
  deepBreath:       'Inhale slowly through the nose for 4 counts, expanding your belly. Hold 4 counts. Exhale fully through the mouth for 6 counts. Activates the parasympathetic system to lower heart rate.',
  hamstringStretch: 'Stand and extend one leg forward with heel on the ground, toes up. Hinge at the hips and lean forward gently. Lengthens the hamstrings and reduces lower-back tightness after leg workouts.',
  highKnees:        'Run in place, driving your knees up toward your chest with each step. Pump your arms to stay coordinated. Elevates heart rate, activates hip flexors, and improves running cadence.',
  hipCircles:       'Stand with feet shoulder-width apart and hands on hips. Draw large circles with your hips, going clockwise then counter-clockwise. Lubricates the hip joint and warms up the lower body.',
  hipThrust:        'Sit with your upper back against a bench, feet flat, barbell across hips. Drive hips upward by squeezing glutes until your body forms a straight line. The most effective glute-building movement.',
  inclineWalk:      'Set treadmill to 10–15% incline at a brisk walking pace. Keeps heart rate in the fat-burning zone while minimizing joint impact. Targets calves, hamstrings, and glutes.',
  jumpRope:         'Swing the rope overhead and jump over it with both feet, landing softly on the balls of your feet. Improves coordination, calf strength, and cardiovascular endurance simultaneously.',
  jumpingJacks:     'Start with feet together and arms at sides. Jump your feet out wide while raising arms overhead, then return. A classic full-body warm-up that gets blood flowing to every major muscle group.',
  kbSwing:          'Stand with feet shoulder-width apart, hinge at the hips and swing the kettlebell between your legs, then drive hips forward explosively to swing it to shoulder height. A powerful posterior-chain movement.',
  latPulldown:      'Grip the bar slightly wider than shoulder width. Pull it down to your upper chest, squeezing shoulder blades together. This is the foundation of back width training and builds the V-taper shape.',
  lateralRaise:     'Hold dumbbells at your sides, palms facing in. Raise arms out to the sides until they reach shoulder height, leading with your elbows. Isolates the medial deltoid for broader, rounder shoulders.',
  lunge:            'Step one foot forward and lower your back knee toward the floor, keeping your front shin vertical. Push through the front heel to return. Builds quad and glute strength with excellent balance training.',
  mountainClimber:  'Start in a high plank. Drive one knee toward your chest, then quickly switch legs in a running motion. Keeps core braced throughout. Combines cardio with core stability and hip-flexor strength.',
  pigeonPose:       'From a lunge position, lower the front shin to the mat and extend the back leg straight behind you. Fold forward for a deeper stretch. Opens the hip rotators and relieves tension in the IT band.',
  plank:            'Support yourself on forearms and toes, keeping your body in a straight line from head to heels. Brace your core, squeeze your glutes, and breathe normally. The foundation of all core strength and stability.',
  pushup:           'Start in a high plank with hands slightly wider than shoulders. Lower your chest to the floor by bending the elbows, then press back up. Builds chest, tricep, and anterior shoulder strength with no equipment.',
  quadStretch:     'Stand on one leg, bend the other knee and pull the foot toward your glutes. Keep knees together and stand tall. Stretches the quadriceps and hip flexor, essential after any squat or lunge work.',
  rdl:              'Hold dumbbells in front of your thighs. Hinge forward at the hips, pushing them back while keeping the back flat and a slight knee bend. Lower until you feel a deep hamstring stretch, then drive hips forward.',
  russianTwist:     'Sit on the floor, lean back slightly, feet raised or on the floor. Rotate your torso side to side, touching the ground or passing a weight each rep. Targets the obliques and transverse abdominis.',
  shoulderPress:    'Hold dumbbells at ear level with elbows at 90°. Press overhead until arms are fully extended, then lower with control. The premier shoulder-building movement for strength and size.',
  shoulderStretch:  'Pull one arm horizontally across your chest with the opposite hand pressing just above the elbow. Hold 30 seconds. Releases tension in the rear deltoid and upper back after pushing movements.',
  spinalTwist:      'Sit tall, cross one foot over the opposite thigh, and twist your torso toward the raised knee using your opposite elbow for leverage. Decompresses spinal discs and improves rotational mobility.',
  squat:            'Stand with feet shoulder-width apart. Break at the hips and knees simultaneously, lowering until thighs are at least parallel to the floor. Drive through the full foot to stand. The king of lower-body exercises.',
};

export const EXERCISE_YT_SEARCH = {
  armCircles:       'arm circles warm up exercise how to',
  bicepCurl:        'dumbbell bicep curl proper form',
  burpee:           'how to do a burpee correct form',
  catCow:           'cat cow stretch yoga how to',
  chestPress:       'dumbbell chest press proper form',
  childPose:        "child's pose yoga how to",
  deepBreath:       'deep breathing exercise diaphragm',
  hamstringStretch: 'standing hamstring stretch how to',
  highKnees:        'high knees exercise proper form',
  hipCircles:       'hip circles warm up mobility',
  hipThrust:        'barbell hip thrust proper form glutes',
  inclineWalk:      'treadmill incline walk fat burn workout',
  jumpRope:         'jump rope technique beginners',
  jumpingJacks:     'jumping jacks how to proper form',
  kbSwing:          'kettlebell swing proper form',
  latPulldown:      'lat pulldown proper form back',
  lateralRaise:     'dumbbell lateral raise side delts',
  lunge:            'reverse lunge proper form',
  mountainClimber:  'mountain climbers exercise form',
  pigeonPose:       'pigeon pose yoga hip stretch',
  plank:            'plank proper form core',
  pushup:           'push up proper form technique',
  quadStretch:      'standing quad stretch how to',
  rdl:              'romanian deadlift dumbbell form hamstrings',
  russianTwist:     'russian twist exercise obliques',
  shoulderPress:    'dumbbell shoulder press overhead form',
  shoulderStretch:  'shoulder cross body stretch',
  spinalTwist:      'seated spinal twist yoga',
  squat:            'barbell squat proper form depth',
};
