export const GUT_STEPS = [
  { icon:"🥗", title:"Overhaul Your Diet",       ytQuery:"gut health diet plan whole foods anti-inflammatory",
    body:"Focus on whole, plant-based foods. Aim for ~30 different plant foods per week. Avoid refined sugars, artificial sweeteners and processed foods. Choose lean proteins, healthy fats (olive oil, avocado), and anti-inflammatory herbs like ginger and turmeric." },
  { icon:"💧", title:"Hydrate Well",              ytQuery:"how much water to drink gut health digestion",
    body:"Drink ~8 cups (64 oz) of water per day. Herbal teas — green tea or peppermint — provide antioxidants and reduce gut inflammation." },
  { icon:"🍶", title:"Probiotics & Prebiotics",   ytQuery:"probiotics prebiotics gut microbiome foods",
    body:"Eat fermented foods: yogurt, kefir, sauerkraut, kimchi or miso. Add prebiotic-rich foods like garlic, onions, asparagus and oats. Together they support the gut barrier and ease anxiety via the gut–brain axis." },
  { icon:"🌾", title:"Boost Fiber & Move",        ytQuery:"high fiber foods gut health exercise bowel",
    body:"Aim for high-fiber intake — oats, quinoa, chia seeds, lentils and dark leafy greens. Pair with 30+ minutes of daily movement to promote healthy bowel contractions." },
  { icon:"😴", title:"Prioritize Sleep (7–8 hrs)",ytQuery:"sleep gut health microbiome circadian rhythm",
    body:"Good sleep heals the gut lining and regulates hormones. Allow 7–8 hours per night, aligned with your natural circadian rhythm." },
  { icon:"🧘", title:"Manage Stress",             ytQuery:"stress gut health mindfulness breathing meditation",
    body:"Chronic stress worsens gut inflammation. Practice mindfulness, meditation or gentle breathing. Power off screens an hour before bed." },
  { icon:"🚫", title:"Avoid Toxins",              ytQuery:"alcohol gut microbiome damage avoid toxins",
    body:"Limit alcohol, tobacco and unnecessary medications that kill healthy gut bacteria. These toxins destroy gut lining cells and beneficial microbes." },
  { icon:"🤝", title:"Support Social Well-Being", ytQuery:"social connection gut health wellbeing",
    body:"Positive relationships benefit gut health. Laughter and companionship may even boost microbiome diversity." },
];

export const GUT_SIGNS = [
  { icon:"😣", title:"Chronic Discomfort",   desc:"Regular bloating, gas, irregular stools, or stomach pain that won't go away.", color:"#ff6060" },
  { icon:"🧠", title:"Brain Fog / Fatigue",  desc:"Low energy or difficulty focusing can arise from poor nutrient absorption.", color:"#b388ff" },
  { icon:"😰", title:"Mood Swings / Anxiety",desc:"GI tract irritation sends signals to your brain, worsening mood and anxiety.", color:"#ffb84d" },
  { icon:"🤧", title:"Poor Immunity",        desc:"Frequent colds may signal gut inflammation undermining your immune system.", color:"#2de2c8" },
];

export const GUT_RECIPES = [
  {
    icon:"🥤", title:"Probiotic Smoothie", tag:"Breakfast", color:"#2de2c8",
    desc:"Live cultures, ~10g fiber, antioxidants — all in one glass.",
    time:"5 min", calories:"~280 kcal", servings:"1",
    benefits:["🦠 Boosts good bacteria","⚡ Sustained energy","💧 Hydrating","🌿 Anti-inflammatory"],
    ingredients:[
      { emoji:"🥛", item:"1 cup kefir (plain, full-fat)" },
      { emoji:"🍓", item:"½ cup mixed berries (frozen or fresh)" },
      { emoji:"🍌", item:"1 ripe banana" },
      { emoji:"🥬", item:"1 large handful of spinach" },
      { emoji:"🫚", item:"1 tbsp chia seeds" },
      { emoji:"🫚", item:"1 tbsp ground flaxseed" },
      { emoji:"🫚", item:"½ tsp fresh grated ginger" },
      { emoji:"🍯", item:"1 tsp honey (optional)" },
    ],
    steps:[
      "Add kefir and spinach to the blender first — this helps it blend smoothly.",
      "Add the frozen berries and banana.",
      "Sprinkle in chia seeds, flaxseed and grated ginger.",
      "Blend on high for 45–60 seconds until completely smooth.",
      "Taste and add honey if you prefer a little sweetness.",
      "Pour into a glass and drink immediately for maximum probiotic benefit.",
      "🌟 Pro tip: Drink within 15 minutes of blending so the live cultures stay active.",
    ],
  },
  {
    icon:"🥬", title:"Fermented Snack Plate", tag:"Snack", color:"#4fffb0",
    desc:"A quick probiotic hit — ready in 2 minutes, gut-repairing all day.",
    time:"2 min", calories:"~180 kcal", servings:"1",
    benefits:["🦠 Diverse probiotics","🛡️ Strengthens gut lining","😌 Reduces bloating","🧠 Gut-brain support"],
    ingredients:[
      { emoji:"🥬", item:"3 tbsp sauerkraut (unpasteurised)" },
      { emoji:"🌶️", item:"3 tbsp kimchi" },
      { emoji:"🥛", item:"½ cup Greek yogurt (full-fat)" },
      { emoji:"🍯", item:"1 tsp raw honey" },
      { emoji:"🫐", item:"Small handful of blueberries" },
      { emoji:"🌰", item:"1 tbsp mixed seeds (pumpkin, sunflower)" },
      { emoji:"🫚", item:"Drizzle of extra-virgin olive oil" },
    ],
    steps:[
      "Spoon the Greek yogurt into the centre of a small plate or bowl.",
      "Pile the sauerkraut on one side and the kimchi on the other.",
      "Scatter blueberries and mixed seeds over the yogurt.",
      "Drizzle honey and olive oil over everything.",
      "Eat slowly and mindfully — chewing activates digestive enzymes.",
      "🌟 Always choose unpasteurised sauerkraut and kimchi — pasteurisation kills the live cultures.",
    ],
  },
  {
    icon:"🍲", title:"Bone Broth Miso Soup", tag:"Any meal", color:"#ffb84d",
    desc:"Collagen-rich gut lining repair in a warm, comforting bowl.",
    time:"10 min", calories:"~120 kcal", servings:"2",
    benefits:["🔧 Repairs gut lining","💪 Collagen & glutamine","😴 Calming & warming","🛡️ Immune support"],
    ingredients:[
      { emoji:"🍖", item:"2 cups quality bone broth (chicken or beef)" },
      { emoji:"🌊", item:"2 cups water" },
      { emoji:"🟡", item:"2 tbsp white miso paste" },
      { emoji:"🥬", item:"1 sheet dried nori, torn into pieces" },
      { emoji:"🧅", item:"2 spring onions, thinly sliced" },
      { emoji:"🟩", item:"100g silken tofu, cubed" },
      { emoji:"🫚", item:"1 tsp sesame oil" },
      { emoji:"🌿", item:"Small handful of fresh coriander" },
    ],
    steps:[
      "Gently warm the bone broth and water together in a saucepan over medium-low heat.",
      "Do not boil — high heat destroys the beneficial enzymes.",
      "Dissolve miso paste in a small cup of warm broth, then stir back into the pot.",
      "Add tofu, nori and spring onions. Simmer for 2–3 minutes.",
      "Remove from heat, drizzle sesame oil and top with coriander.",
      "Sip slowly — ideal 20 minutes before a main meal to prime digestion.",
      "🌟 Never add miso to boiling water. Keep the heat gentle to preserve its probiotic enzymes.",
    ],
  },
  {
    icon:"🥗", title:"Prebiotic Power Bowl", tag:"Lunch", color:"#b388ff",
    desc:"30+ plant diversity in one bowl — feeds your good bacteria for hours.",
    time:"20 min", calories:"~420 kcal", servings:"2",
    benefits:["🌿 30+ plants in one meal","🌾 High fibre (18g)","🔥 Anti-inflammatory","⚡ Sustained energy"],
    ingredients:[
      { emoji:"🌾", item:"½ cup quinoa, rinsed and cooked" },
      { emoji:"🫘", item:"½ cup green lentils, cooked" },
      { emoji:"🌿", item:"6 asparagus spears, chopped" },
      { emoji:"🧅", item:"½ red onion, thinly sliced" },
      { emoji:"🍎", item:"½ green apple, cubed" },
      { emoji:"🫑", item:"½ cup roasted chickpeas" },
      { emoji:"🥬", item:"2 handfuls of rocket / mixed greens" },
      { emoji:"🫚", item:"2 tbsp extra-virgin olive oil" },
      { emoji:"🍋", item:"Juice of ½ lemon" },
      { emoji:"🌿", item:"Fresh parsley and mint to serve" },
    ],
    steps:[
      "Cook quinoa in water for 12–15 min. Drain and let cool slightly.",
      "Toss asparagus and chickpeas in olive oil, roast at 200°C for 15 min until crisp.",
      "Whisk together olive oil, lemon juice, salt and pepper for the dressing.",
      "Build the bowl: greens first, then quinoa, lentils, and roasted veg.",
      "Top with apple, red onion, herbs and a generous drizzle of dressing.",
      "Eat within 20 minutes of assembling for best texture.",
      "🌟 The more variety the better — swap in any seasonal veg to keep hitting your 30-plant-per-week target.",
    ],
  },
  {
    icon:"🍵", title:"Golden Gut Tea", tag:"Evening", color:"#ff5fa0",
    desc:"A warming anti-inflammatory ritual to heal your gut lining overnight.",
    time:"5 min", calories:"~45 kcal", servings:"1",
    benefits:["🌙 Calms gut inflammation","😴 Promotes restful sleep","🛡️ Antioxidant rich","🧘 Stress reducing"],
    ingredients:[
      { emoji:"💛", item:"1 tsp ground turmeric" },
      { emoji:"🫚", item:"½ tsp ground ginger (or 1 cm fresh)" },
      { emoji:"🖤", item:"Pinch of black pepper (activates turmeric)" },
      { emoji:"🥛", item:"1½ cups warm oat milk or coconut milk" },
      { emoji:"🍯", item:"1 tsp raw honey" },
      { emoji:"🫚", item:"½ tsp cinnamon" },
      { emoji:"🫚", item:"¼ tsp coconut oil (optional, helps absorption)" },
    ],
    steps:[
      "Warm the milk gently in a small saucepan over low heat — do not boil.",
      "Whisk in turmeric, ginger, cinnamon and black pepper.",
      "Add coconut oil if using — it helps your body absorb curcumin from turmeric.",
      "Pour into a mug and stir in honey once slightly cooled.",
      "Drink 30–60 minutes before bed for best gut-healing effect.",
      "Make it a nightly ritual to signal wind-down to your nervous system.",
      "🌟 The black pepper is essential — it increases turmeric absorption by up to 2000%.",
    ],
  },
];

export const DAILY_CHECKLIST = [
  { id:"probiotic", label:"Morning Probiotic (empty stomach)", icon:"🦠" },
  { id:"water",     label:"Drink 8 cups of water",             icon:"💧" },
  { id:"fiber",     label:"Hit 25g fiber target today",        icon:"🌾" },
  { id:"nosugar",   label:"No refined sugars / processed food",icon:"🚫" },
  { id:"walk",      label:"10-min post-meal digestive walk",   icon:"🚶" },
  { id:"sleep",     label:"In bed by 10:30 PM",                icon:"😴" },
  { id:"fermented", label:"Eat a fermented food today",        icon:"🍶" },
  { id:"mindful",   label:"5-min mindfulness / breathing",     icon:"🧘" },
];

export const SYMPTOM_OPTIONS = [
  { id:"bloating",  label:"Bloating",         icon:"😮‍💨", color:"#ffb84d" },
  { id:"energy",    label:"Good Energy",      icon:"⚡",   color:"#4fffb0" },
  { id:"digestion", label:"Easy Digestion",   icon:"✅",   color:"#2de2c8" },
  { id:"brainfog",  label:"Brain Fog",        icon:"🌫️",  color:"#b388ff" },
  { id:"cramps",    label:"Cramps / Pain",    icon:"😣",   color:"#ff6060" },
  { id:"mood",      label:"Stable Mood",      icon:"😊",   color:"#5bc8ff" },
  { id:"irregular", label:"Irregular Stools", icon:"⚠️",  color:"#ff9100" },
  { id:"sleep",     label:"Slept Well",       icon:"😴",   color:"#ff5fa0" },
];
