export const REAL = {
  stepHistory:  [3752,5755,6843,3890,11607,9595,10067,5694,3144,5659,4273,11707,12390,7322,1006,11642,8662,4124,1066,1123,536,435,2784,9194,10731,3364,3575,3449,17556,5943],
  kcalHistory:  [148,526,257,214,666,170,527,622,56,550,235,631,502,369,18,364,296,73,21,20,10,8,50,160,537,172,63,59,764,210],
  rhrHistory:   [0,0,59,83,71,80,0,90,80,0,69,80,85,72,71,0,86,72,0,0,0,0,0,0,74,59,0,0,66,70],
  exHistory:    [30,89,28,13,115,0,93,119,70,18,95,43,30,0,39,33,0,0,0,0,0,0,0,71,8,0,0,0,142,22],
  distHistory:  [2450,4430,5044,2819,8171,7462,6587,3679,2504,3708,2873,8779,8109,5209,856,7961,5669,3184,917,936,460,357,2116,7007,7487,2308,2790,2625,12457,4040],
  dateLabels:   ["Mar14","Mar15","Mar16","Mar17","Mar18","Mar19","Mar20","Mar21","Mar22","Mar23","Mar24","Mar25","Mar26","Mar27","Mar28","Mar29","Mar30","Mar31","Apr1","Apr2","Apr3","Apr4","Apr5","Apr6","Apr7","Apr8","Apr9","Apr10","Apr11","Apr12"],
  weight: 63.5, rhr: 70, exMin: 22, age: 25,
  stepGoal: 10000, kcalGoal: 500,
};

export const getMuscleGroups = (T) => [
  {
    day:0, name:"Chest", emoji:"🏋️", label:"Chest & Triceps",
    color:T.pink, focus:"Heavy Fat Loss", phase:"follicular", stepGoal: 12000,
    tip:"Follicular phase — estrogen rising. Best window for chest. Push hard today!",
    warmUp: [
      { id:"wu1", name:"Jumping Jacks", anim:"jumpingJacks", sets:"3 min", kcal:20, tip:"Full arm swing, land softly. Raises core temp before lifting." },
      { id:"wu2", name:"Arm Circles",   anim:"armCircles",   sets:"60s each dir", kcal:8, tip:"Big slow circles first, then small fast. Opens up shoulder joint." },
      { id:"wu3", name:"Hip Circles",   anim:"hipCircles",   sets:"30s each way", kcal:6, tip:"Hands on hips, big rotations. Lubricates hip flexors." },
    ],
    main: [
      { id:"m1", name:"Dumbbell Chest Press", anim:"chestPress",   sets:"3 × 15", kcal:55, muscle:"Chest, Triceps", tip:"Lower to chest, press straight up. Squeeze pecs at top." },
      { id:"m2", name:"Incline DB Press",     anim:"chestPress",   sets:"3 × 12", kcal:50, muscle:"Upper Chest",   tip:"30–45° angle. Targets upper chest for lift and toning." },
      { id:"m3", name:"Push-Ups",             anim:"pushup",       sets:"3 × 15", kcal:40, muscle:"Chest, Core",   tip:"Wide hands for chest. Body in a straight line always." },
      { id:"m4", name:"Lateral Raises",       anim:"lateralRaise", sets:"3 × 15", kcal:35, muscle:"Shoulders",     tip:"Lead with elbows. Control on the way down." },
      { id:"m5", name:"Bicep Curl",           anim:"bicepCurl",    sets:"3 × 15", kcal:30, muscle:"Biceps",        tip:"Supinate at top. 3-sec slow lower. No elbow swing." },
      { id:"m6", name:"Lat Pulldown",         anim:"latPulldown",  sets:"3 × 12", kcal:55, muscle:"Back, Lats",    tip:"Wide grip. Pull to upper chest. Squeeze lats at bottom." },
    ],
    coolDown: [
      { id:"cd1", name:"Chest Door Stretch",    anim:"shoulderStretch", sets:"45s", kcal:4, tip:"Arm at 90° on wall/door. Gentle press forward. Feel chest open." },
      { id:"cd2", name:"Shoulder Cross Stretch", anim:"shoulderStretch", sets:"30s each", kcal:3, tip:"Pull arm across chest. Hold 30 seconds each side." },
      { id:"cd3", name:"Child's Pose",           anim:"childPose",       sets:"60s", kcal:4, tip:"Sink hips back to heels. Arms stretched forward. Breathe deep." },
      { id:"cd4", name:"Spinal Twist",           anim:"spinalTwist",     sets:"30s each", kcal:3, tip:"Seated twist. Exhale to rotate deeper. Releases spine." },
      { id:"cd5", name:"Deep Breath Hold",       anim:"deepBreath",      sets:"5 breaths", kcal:2, tip:"Inhale 4 counts, hold 4, exhale 6. Brings HR down fast." },
    ],
  },
  {
    day:1, name:"Legs", emoji:"🦵", label:"Legs & Glutes",
    color:"#f472b6", focus:"Intense Fat Loss", phase:"follicular", stepGoal: 10000,
    tip:"Leg day on follicular = GOLD. Pain tolerance elevated — go heavier!",
    warmUp: [
      { id:"wu1", name:"High Knees",   anim:"highKnees",    sets:"2 min", kcal:25, tip:"Drive knees above hip height. Land on ball of foot. Stay light." },
      { id:"wu2", name:"Hip Circles",  anim:"hipCircles",   sets:"30s each", kcal:6, tip:"Wide circles. Warm up hip flexors before heavy squats and lunges." },
      { id:"wu3", name:"Arm Circles",  anim:"armCircles",   sets:"30s", kcal:5, tip:"Gets blood flowing and shoulders mobile before deadlifts." },
    ],
    main: [
      { id:"m1", name:"Goblet Squat",       anim:"squat",       sets:"4 × 15", kcal:75, muscle:"Quads, Glutes",  tip:"Deep squat — thighs parallel or below. Drive through heels." },
      { id:"m2", name:"Hip Thrust",         anim:"hipThrust",   sets:"4 × 15", kcal:65, muscle:"Glutes",         tip:"Squeeze HARD at top. Best exercise for glute shaping." },
      { id:"m3", name:"Romanian Deadlift",  anim:"rdl",         sets:"3 × 12", kcal:65, muscle:"Hamstrings",     tip:"Hinge at hips. Feel hamstring stretch. Neutral spine always." },
      { id:"m4", name:"Reverse Lunges",     anim:"lunge",       sets:"3 × 12e", kcal:55, muscle:"Quads, Glutes", tip:"Step back, lower back knee to floor. Front shin vertical." },
      { id:"m5", name:"Kettlebell Swings",  anim:"kbSwing",     sets:"3 × 20", kcal:80, muscle:"Glutes, Core",   tip:"Hips drive the swing — not arms. Explosive hip extension." },
    ],
    coolDown: [
      { id:"cd1", name:"Pigeon Pose",         anim:"pigeonPose",       sets:"90s each", kcal:5, tip:"Square hips. Breathe into the tension. Releases tight glutes." },
      { id:"cd2", name:"Hamstring Stretch",   anim:"hamstringStretch", sets:"45s each", kcal:4, tip:"Hinge forward standing. Feel the stretch up back of leg." },
      { id:"cd3", name:"Quad Stretch",        anim:"quadStretch",      sets:"30s each", kcal:3, tip:"Stand on one leg, pull heel to glute. Squeeze core to balance." },
      { id:"cd4", name:"Spinal Twist",        anim:"spinalTwist",      sets:"30s each", kcal:3, tip:"Seated. Exhale into the twist. Decompresses lumbar spine." },
      { id:"cd5", name:"Child's Pose",        anim:"childPose",        sets:"60s", kcal:4, tip:"Hips to heels. Full spine elongation. Breathe slowly." },
    ],
  },
  {
    day:2, name:"Back", emoji:"💪", label:"Back & Posture",
    color:T.teal, focus:"Targeted Fat Loss", phase:"follicular", stepGoal: 12000,
    tip:"Strong back = better posture and faster metabolism. Pull hard.",
    warmUp: [
      { id:"wu1", name:"Jumping Jacks", anim:"jumpingJacks", sets:"2 min", kcal:18, tip:"Gets the whole body warm. Good rhythm before back day." },
      { id:"wu2", name:"Arm Circles",   anim:"armCircles",   sets:"45s each", kcal:6, tip:"Especially important — shoulder health is crucial for pulling movements." },
      { id:"wu3", name:"Hip Circles",   anim:"hipCircles",   sets:"30s", kcal:5, tip:"Loosens up lower back before rows and deadlifts." },
    ],
    main: [
      { id:"m1", name:"Lat Pulldown",       anim:"latPulldown",  sets:"3 × 12", kcal:55, muscle:"Lats",      tip:"Wide grip. Pull to upper chest. Lean back slightly." },
      { id:"m2", name:"Seated Cable Row",   anim:"latPulldown",  sets:"3 × 15", kcal:45, muscle:"Mid Back",  tip:"Full extension then row to navel. Chest stays tall." },
      { id:"m3", name:"Dumbbell RDL",       anim:"rdl",          sets:"3 × 12", kcal:60, muscle:"Back, Hams", tip:"Back muscle activation all the way through hip hinge." },
      { id:"m4", name:"Lateral Raises",     anim:"lateralRaise", sets:"3 × 15", kcal:35, muscle:"Rear Delts", tip:"Crucial for balanced shoulders and posture." },
      { id:"m5", name:"Mountain Climbers",  anim:"mountainClimber", sets:"3 × 30s", kcal:40, muscle:"Core", tip:"Maintain plank. Drives core and hits upper body too." },
    ],
    coolDown: [
      { id:"cd1", name:"Cat-Cow Stretch",     anim:"catCow",           sets:"2 min", kcal:6, tip:"Move with breath. Cow on inhale, cat on exhale. Spine loves this." },
      { id:"cd2", name:"Child's Pose",        anim:"childPose",        sets:"90s", kcal:5, tip:"Decompresses lumbar spine after all that pulling work." },
      { id:"cd3", name:"Shoulder Stretch",    anim:"shoulderStretch",  sets:"30s each", kcal:3, tip:"Cross-body pull. Targets rear delts which get tight after rows." },
      { id:"cd4", name:"Spinal Twist",        anim:"spinalTwist",      sets:"30s each", kcal:3, tip:"Releases rotational tension in the thoracic spine." },
      { id:"cd5", name:"Deep Breath",         anim:"deepBreath",       sets:"5 breaths", kcal:2, tip:"Calms nervous system. Recovery begins here." },
    ],
  },
  {
    day:3, name:"Recover", emoji:"🧘", label:"Active Recovery",
    color:T.green, focus:"Steady State Fat Loss", phase:"follicular", stepGoal: 15000,
    tip:"Recovery is where the gains happen. Light movement and deep stretching today.",
    warmUp: [
      { id:"wu1", name:"Arm Circles",  anim:"armCircles",  sets:"60s", kcal:5, tip:"Gentle circles to get joints moving. No intensity needed today." },
      { id:"wu2", name:"Hip Circles",  anim:"hipCircles",  sets:"45s", kcal:4, tip:"Loosen up the hips — they got worked the last two days." },
    ],
    main: [
      { id:"m1", name:"Incline Walk",      anim:"inclineWalk",    sets:"30 min", kcal:180, muscle:"Full Body", tip:"12–15% incline. 3.5–4 mph. Hands off rails! Fat burn, low impact." },
      { id:"m2", name:"Plank Hold",        anim:"plank",          sets:"3 × 45s", kcal:15, muscle:"Core",     tip:"Squeeze everything. No hip sag. Breathe steadily." },
      { id:"m3", name:"Russian Twist",     anim:"russianTwist",   sets:"3 × 20", kcal:25, muscle:"Obliques",  tip:"Hold weight. Lean 45°. Rotate fully each side." },
      { id:"m4", name:"Mountain Climbers", anim:"mountainClimber", sets:"3 × 30s", kcal:35, muscle:"Core",    tip:"Keep hips level. Drive knees fast to chest." },
    ],
    coolDown: [
      { id:"cd1", name:"Pigeon Pose",       anim:"pigeonPose",       sets:"90s each", kcal:5, tip:"Your hips need this after incline walking. Stay here longer if needed." },
      { id:"cd2", name:"Cat-Cow",           anim:"catCow",           sets:"2 min", kcal:5, tip:"Counteracts all that forward lean from incline walking." },
      { id:"cd3", name:"Hamstring Stretch", anim:"hamstringStretch", sets:"60s each", kcal:4, tip:"Hamstrings tighten from walking. Essential stretch." },
      { id:"cd4", name:"Child's Pose",      anim:"childPose",        sets:"90s", kcal:4, tip:"Full body release. Breathe into lower back. Stay as long as you like." },
      { id:"cd5", name:"Spinal Twist",      anim:"spinalTwist",      sets:"45s each", kcal:3, tip:"Wrings out tension from the spine. Great digestive benefit too." },
    ],
  },
  {
    day:4, name:"Shoulders", emoji:"🔺", label:"Shoulders & Arms",
    color:T.amber, focus:"Explosive Fat Loss", phase:"follicular", stepGoal: 12000,
    tip:"Energy building toward ovulation. Great day for shoulder press PRs!",
    warmUp: [
      { id:"wu1", name:"Arm Circles",   anim:"armCircles",   sets:"60s each", kcal:7, tip:"Full range — essential warm-up before overhead pressing." },
      { id:"wu2", name:"Jumping Jacks", anim:"jumpingJacks", sets:"2 min", kcal:20, tip:"Full body warm, then focus shifts to upper body." },
      { id:"wu3", name:"Hip Circles",   anim:"hipCircles",   sets:"30s", kcal:4, tip:"Lower body stays active even on arm days." },
    ],
    main: [
      { id:"m1", name:"Shoulder Press",  anim:"shoulderPress", sets:"3 × 12", kcal:55, muscle:"Shoulders",      tip:"Press overhead. Full extension. Core tight throughout." },
      { id:"m2", name:"Lateral Raises",  anim:"lateralRaise",  sets:"3 × 15", kcal:35, muscle:"Side Delts",    tip:"Lead with elbows. Slight forward lean. Control descent." },
      { id:"m3", name:"Bicep Curl",      anim:"bicepCurl",     sets:"3 × 15", kcal:30, muscle:"Biceps",         tip:"Supinate at top. 3-sec slow eccentric. Don't swing." },
      { id:"m4", name:"Lat Pulldown",    anim:"latPulldown",   sets:"3 × 12", kcal:55, muscle:"Back",           tip:"Back balances shoulder pressing. Never skip it." },
      { id:"m5", name:"Jump Rope HIIT",  anim:"jumpRope",      sets:"10 min", kcal:120, muscle:"Full Body",     tip:"45s on / 15s off. Stay on toes. Wrists do the turning." },
    ],
    coolDown: [
      { id:"cd1", name:"Shoulder Stretch",  anim:"shoulderStretch",  sets:"45s each", kcal:4, tip:"Cross-body arm pull. Rear delts need this after pressing." },
      { id:"cd2", name:"Spinal Twist",      anim:"spinalTwist",      sets:"30s each", kcal:3, tip:"Decompress after all the pushing and pulling." },
      { id:"cd3", name:"Hamstring Stretch", anim:"hamstringStretch", sets:"45s", kcal:3, tip:"Jump rope tightens calves and hamstrings — stretch them out." },
      { id:"cd4", name:"Child's Pose",      anim:"childPose",        sets:"60s", kcal:3, tip:"Full reset. Spine lengthens, shoulders release." },
      { id:"cd5", name:"Deep Breath",       anim:"deepBreath",       sets:"5 breaths", kcal:2, tip:"Activates parasympathetic nervous system. Your recovery starts now." },
    ],
  },
  {
    day:5, name:"Core", emoji:"⚡", label:"Core & HIIT",
    color:T.violet, focus:"High Calorie Fat Burn", phase:"ovulation", stepGoal: 13000,
    tip:"Ovulation — PEAK power! Your best HIIT session of the month. Crush it.",
    warmUp: [
      { id:"wu1", name:"High Knees",    anim:"highKnees",    sets:"2 min", kcal:28, tip:"Get heart rate up fast. Full drive — arms pump hard." },
      { id:"wu2", name:"Jumping Jacks", anim:"jumpingJacks", sets:"90s", kcal:18, tip:"Transition from high knees. Keep the HR elevated." },
      { id:"wu3", name:"Hip Circles",   anim:"hipCircles",   sets:"30s", kcal:5, tip:"Core exercises need mobile hips. This does it fast." },
    ],
    main: [
      { id:"m1", name:"Plank Hold",         anim:"plank",          sets:"3 × 45s", kcal:15, muscle:"Core",     tip:"Squeeze abs, glutes, quads — all at once. No holding breath." },
      { id:"m2", name:"Russian Twist",      anim:"russianTwist",   sets:"3 × 20", kcal:25, muscle:"Obliques",  tip:"Add weight. Lean 45°. Waist definition lives here." },
      { id:"m3", name:"Mountain Climbers",  anim:"mountainClimber", sets:"4 × 30s", kcal:40, muscle:"Core",   tip:"Fast tempo. Cardio AND core. Keep plank locked." },
      { id:"m4", name:"Burpees",            anim:"burpee",         sets:"4 × 10", kcal:80, muscle:"Full Body",  tip:"Best fat burner. Squat → plank → push-up → jump." },
      { id:"m5", name:"Kettlebell Swings",  anim:"kbSwing",        sets:"4 × 20", kcal:90, muscle:"Glutes, Core", tip:"Hip drive! KB feels weightless at top when done right." },
    ],
    coolDown: [
      { id:"cd1", name:"Cat-Cow Stretch",   anim:"catCow",           sets:"2 min", kcal:6, tip:"After HIIT, spine needs decompression. Breathe into every prep." },
      { id:"cd2", name:"Child's Pose",      anim:"childPose",        sets:"90s", kcal:5, tip:"Full reset after burpees and swings. Take your time here." },
      { id:"cd3", name:"Pigeon Pose",       anim:"pigeonPose",       sets:"90s each", kcal:5, tip:"Hip flexors and glutes get tight from HIIT. Hold it." },
      { id:"cd4", name:"Spinal Twist",      anim:"spinalTwist",      sets:"30s each", kcal:3, tip:"Wrings out lactic acid from the core and lower back." },
      { id:"cd5", name:"Deep Breath",       anim:"deepBreath",       sets:"5 breaths", kcal:2, tip:"Slow inhale–hold–exhale. Brings cortisol down after HIIT." },
    ],
  },
  {
    day:6, name:"Full Body", emoji:"🔥", label:"Full Body Burn",
    color:"#fb7185", focus:"Maximal Fat Loss", phase:"ovulation", stepGoal: 10000,
    tip:"Peak power day! Compound moves = max calorie burn. Leave it all there.",
    warmUp: [
      { id:"wu1", name:"High Knees",    anim:"highKnees",    sets:"2 min", kcal:28, tip:"Max drive. Full body is about to get taxed — prime it right." },
      { id:"wu2", name:"Arm Circles",   anim:"armCircles",   sets:"45s each", kcal:6, tip:"Shoulders will be involved in every exercise today." },
      { id:"wu3", name:"Jumping Jacks", anim:"jumpingJacks", sets:"90s", kcal:18, tip:"Gets every joint warm and every muscle group primed." },
    ],
    main: [
      { id:"m1", name:"Dumbbell Deadlift",  anim:"rdl",          sets:"4 × 12", kcal:80, muscle:"Hamstrings, Back", tip:"Full hinge. Hips drive standing. Biggest calorie burn." },
      { id:"m2", name:"Squat",             anim:"squat",         sets:"4 × 15", kcal:75, muscle:"Quads, Glutes",    tip:"Heels down. Deep as possible. Drive up explosively." },
      { id:"m3", name:"Reverse Lunges",    anim:"lunge",         sets:"3 × 12e", kcal:55, muscle:"Glutes, Quads",  tip:"Full step. Front knee tracks over toes. Control it." },
      { id:"m4", name:"Kettlebell Swings", anim:"kbSwing",       sets:"4 × 20", kcal:90, muscle:"Glutes, Core",    tip:"Explosive! Hip snap sends KB up. Core stays tight." },
      { id:"m5", name:"Push-Ups",          anim:"pushup",        sets:"3 × 15", kcal:40, muscle:"Chest, Core",     tip:"Wide hands. Chest to floor. Explosive press up." },
      { id:"m6", name:"Burpees",           anim:"burpee",        sets:"3 × 10", kcal:80, muscle:"Full Body",       tip:"Last exercise. Everything you have left — pour it in." },
    ],
    coolDown: [
      { id:"cd1", name:"Hamstring Stretch", anim:"hamstringStretch", sets:"60s each", kcal:5, tip:"Hamstrings worked hard from deadlifts and squats. Honour them." },
      { id:"cd2", name:"Pigeon Pose",       anim:"pigeonPose",       sets:"90s each", kcal:5, tip:"Hip flexors and glutes fire in every compound. This is non-negotiable." },
      { id:"cd3", name:"Cat-Cow Stretch",   anim:"catCow",           sets:"2 min", kcal:6, tip:"Lower back decompression after heavy lifting. Go slow." },
      { id:"cd4", name:"Child's Pose",      anim:"childPose",        sets:"90s", kcal:4, tip:"Full body release. You earned this. Breathe into every tight spot." },
      { id:"cd5", name:"Deep Breath",       anim:"deepBreath",       sets:"5 breaths", kcal:2, tip:"Recovery begins with the breath. Inhale 4, hold 4, exhale 6." },
    ],
  },
];
